//Constants for ACCOUNT_SELECTION
export const ACCOUNT_SELECTION_REQUEST = 'ACCOUNT_SELECTION_REQUEST'
export const ACCOUNT_SELECTION_SUCCESS = 'ACCOUNT_SELECTION_SUCCESS'
export const ACCOUNT_SELECTION_FAIL = 'ACCOUNT_SELECTION_FAIL'