//Constants for INBOUND_1STEP_RECEIVING_TALLYNUMBER
export const INBOUND_1STEP_RECEIVING_TALLY_REQUEST =
  "INBOUND_1STEP_RECEIVING_TALLY_REQUEST";
export const INBOUND_1STEP_RECEIVING_TALLY_SUCCESS =
  "INBOUND_1STEP_RECEIVING_TALLY_SUCCESS";
export const INBOUND_1STEP_RECEIVING_TALLY_FAIL =
  "INBOUND_1STEP_RECEIVING_TALLY_FAIL";

//Constants for INBOUND_1STEP_RECEIVING_LOCATION
export const INBOUND_1STEP_RECEIVING_LOCATION_REQUEST =
  "INBOUND_1STEP_RECEIVING_LOCATION_REQUEST";
export const INBOUND_1STEP_RECEIVING_LOCATION_SUCCESS =
  "INBOUND_1STEP_RECEIVING_LOCATION_SUCCESS";
export const INBOUND_1STEP_RECEIVING_LOCATION_FAIL =
  "INBOUND_1STEP_RECEIVING_LOCATION_FAIL";

//Constants for INBOUND_1STEP_RECEIVING_ITEM
export const INBOUND_1STEP_RECEIVING_SAVE_REQUEST =
  "INBOUND_1STEP_RECEIVING_SAVE_REQUEST";
export const INBOUND_1STEP_RECEIVING_SAVE_SUCCESS =
  "INBOUND_1STEP_RECEIVING_SAVE_SUCCESS";
export const INBOUND_1STEP_RECEIVING_SAVE_FAIL =
  "INBOUND_1STEP_RECEIVING_SAVE_FAIL";
