//Constants for INBOUND_TALLYNUMBER
export const INBOUND_TALLY_REQUEST = 'INBOUND_TALLY_REQUEST'
export const INBOUND_TALLY_SUCCESS = 'INBOUND_TALLY_SUCCESS'
export const INBOUND_TALLY_FAIL = 'INBOUND_TALLY_FAIL'

//Constants for INBOUND_ITEM
export const INBOUND_ITEM_REQUEST = 'INBOUND_ITEM_REQUEST'
export const INBOUND_ITEM_SUCCESS = 'INBOUND_ITEM_SUCCESS'
export const INBOUND_ITEM_FAIL = 'INBOUND_ITEM_FAIL'
