//Constants for INBOUND_PUTAWAY_TALLYNUMBER
export const INBOUND_PUTAWAY_TALLY_REQUEST = "INBOUND_PUTAWAY_TALLY_REQUEST";
export const INBOUND_PUTAWAY_TALLY_SUCCESS = "INBOUND_PUTAWAY_TALLY_SUCCESS";
export const INBOUND_PUTAWAY_TALLY_FAIL = "INBOUND_PUTAWAY_TALLY_FAIL";

//Constants for INBOUND_PUTAWAY_ITEM
export const INBOUND_PUTAWAY_LOCATION_REQUEST =
  "INBOUND_PUTAWAY_LOCATION_REQUEST";
export const INBOUND_PUTAWAY_LOCATION_SUCCESS =
  "INBOUND_PUTAWAY_LOCATION_SUCCESS";
export const INBOUND_PUTAWAY_LOCATION_FAIL = "INBOUND_PUTAWAY_LOCATION_FAIL";

//Constants for INBOUND_PUTAWAY_SAVE
export const INBOUND_PUTAWAY_SAVE_REQUEST = "INBOUND_PUTAWAY_SAVE_REQUEST";
export const INBOUND_PUTAWAY_SAVE_SUCCESS = "INBOUND_PUTAWAY_SAVE_SUCCESS";
export const INBOUND_PUTAWAY_SAVE_FAIL = "INBOUND_PUTAWAY_SAVE_FAIL";
